name: EpicGamesFreeGamesResetCookie

on:
  workflow_dispatch:

env:
  APP_NAME: ${{ secrets.APP_NAME }}
  HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
  TEMPORARY_EMAIL_COOKIE: ${{ secrets.TEMPORARY_EMAIL_COOKIE }}

jobs:
  update_app:
    name: Create EpicGamesFreeGames app on Heroku, build, and deploy.
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1
    - run: curl https://cli-assets.heroku.com/install.sh | sh
    - run: sudo apt-get update && sudo apt-get install jq openssl redis -y
    - run: bash deploy_update_app.sh -a $APP_NAME -t cookie